# ansible -i hosts-live all -m shell -a "date"
- hosts: all
  become: yes
  become_user: www-data

  tasks:
  - name: Whoami to run the Ansible Playbook
    shell: whoami

  - name: Job NTP sync
    command: date
    register: msg_date
    become_user: root

  - debug: msg="{{ msg_date.stdout }}"

  - debug: msg="{{ msg_date.stderr }}"
